#!/bin/bash
set -ev
set -o pipefail

dest_dir=$1

mkdir -p $dest_dir
cd $dest_dir
curl -Lo packer.zip https://releases.hashicorp.com/packer/0.10.0/packer_0.10.0_linux_amd64.zip
unzip packer.zip
rm packer.zip

