language: bash

env:
  global:
    - PATH="/tmp/ci-tools:$PATH"
    - secure: "QFsJamGFIC8FfsR22CTaQJFifLzie/+mYP+XmWnnMitODzY6WO2BzZxxnWlOUXCF0C8MNTZXCid/zuFhmnBGwNf2fL2zbYm40o73uKIeAvU3/0WrVRupjrBUO4DLrrcffHrz0E+XtDQ9ty2Q/SaWhwOephwhh/eOL0BjfVKyOr19JfVN7rFnNfGWUuqxBmC03AIQKD7exl10oxnHUwpO5GzaX26vQx4KIrhLMk00tJctFYR6dPpgv9HYi/xyV6OYACmfM3EyGq2wSvAGnJCC8om0/5QspjDDfOw4Im5okuqwXH0DoSehl4dHwbiiIIQAir4aZHfDlaqEoEzS6gZscfcRig/ZWLLLE8yIAK1X+qJ5242MTySPVrUFzSsmaNzgNGBFJGsMZe7SogAzTr/qf16RWh/7EbldMH74rbpn7wW7c6NhQTrN7p9IROGRiJ0Pg8eGArmXA4r3ZQ9pQjhA7HsdQXKDASaMeGHCQSpB7DBTTlBqLBRyYWCbPEuWnNzajYMO8fd49WCGDqgd8+8uPYgH0007f5kFhvfYrlgIxh59yAgu1CY8cii178fbkfMGxEWbd1oIiRk95YXLTxFsZQzbCYBD3BW9jZf0fFtgEfBVu5EaEhewgCI6nrwcb7OgXKXyHAQ92O4oe9d9+60eJpmQkCPZy5KyMbFJY4zxTpk=" # GITCRYPT_PASS
  matrix:
    - COMMAND="cd ami && ./.travis/script"
    - COMMAND="cd cmd/ranch && ./.travis/script"

install:
  - curl -sSL https://github.com/goodeggs/travis-utils/raw/master/install-ci-tools.sh | CACHE_DIR=/tmp/ci-tools sh -s -- go=1.12.7 git-crypt
  - git-crypt-unlock
  - echo $TRAVIS_COMMIT_RANGE

script: eval "$COMMAND"

