sudo: required
dist: trusty

language: go
go:
  - 1.6

env:
  matrix:
    - COMMAND="cd ami && ./.travis/script"
    - COMMAND="cd cmd/ranch && ./.travis/script"

install:
  - ./.travis/install-git-crypt
  - echo $TRAVIS_COMMIT_RANGE

script: eval "$COMMAND"

