sudo: required
dist: trusty

language: go
go:
  - 1.9.2

env:
  matrix:
    - COMMAND="cd ami && ./.travis/script"
    - GOPATH="$PWD" COMMAND="cd src/github.com/goodeggs/platform/cmd/ranch && ./.travis/script"

install:
  - ./.travis/install-git-crypt
  - echo $TRAVIS_COMMIT_RANGE

script: eval "$COMMAND"

