#!/bin/sh
set -e

docker pull yelp/docker-custodian

docker run -a STDOUT -a STDERR --sig-proxy \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --rm \
  yelp/docker-custodian \
  dcgc \
  --max-container-age 24hours \
  --max-image-age 24hours \
  --exclude-image yelp/docker-custodian:latest
