#!/bin/sh
cat >> /etc/goodeggs-environment <-EOF
LOGSPOUT_IMAGE="${var.logspout_image}"
LOGSPOUT_ARGS="sumo://${var.logspout_token}/?host=%H"
ECS_CLUSTER=ecru
ECS_LOGLEVEL=info
ECS_VERSION=v1.13.0
ECS_ENGINE_AUTH_TYPE=dockercfg
ECS_ENGINE_AUTH_DATA={"https://index.docker.io/v1/":{"auth":"${var.docker_auth}","email": "admin@goodeggs.com"}}
ECS_UPDATES_ENABLED=false
EOF
chmod 0400 /etc/goodeggs-environment
