#!/usr/bin/env bash

# Make em quiet
pushd () {
  command pushd "$@" > /dev/null
}

popd () {
  command popd > /dev/null
}

# Exclude containers we don't want effected by limits
EXCLUDES_PATTERN=$(cat <<'EOF' | xargs | sed 's/ /|/g'
sumologic/collector
amazon/amazon-ecs-agent
goodeggs/logspout-goodeggs
convox/api
convox/agent
goodeggs/ranch-api
EOF
)

# Build a list of stuff we DO want to effect
TARGETS=$(docker ps --no-trunc --format '{{.ID}} {{.Image}}' | grep -Ev "$EXCLUDES_PATTERN" | awk '{ print $1; }' | xargs)

# Apply Modifications
for target in $TARGETS; do

  # Disable swap (set memory and swap to same size)
  pushd "/sys/fs/cgroup/memory/docker/$target"
  cat "./memory.limit_in_bytes" > "./memory.memsw.limit_in_bytes"
  popd

  # Limit IOPS for all devices (150 IOPS/Sec to prevent thrashing, reads and writes)
  pushd "/sys/fs/cgroup/blkio/docker/$target"
  devices="$(awk '{print $1;}' ./blkio.throttle.io_service_bytes | uniq | grep -v Total)"
  for device in $devices; do
    echo "$device 150" > ./blkio.throttle.write_iops_device
    echo "$device 150" > ./blkio.throttle.read_iops_device
  done
  popd
done

# No more swap
/sbin/swapoff -a
