#!/bin/sh

if [ "${SUMO_HTTP_TOKEN}z" == "z" ]; then
  >&2 echo "refusing to start logspout: \$SUMO_HTTP_TOKEN is not set."
  exit 1
fi

if [ "${SUMO_HOST}z" == "z" ]; then
  >&2 echo "refusing to start logspout: \$SUMO_HOST is not set."
  exit 1
fi

exec /bin/logspout sumo://${SUMO_HTTP_TOKEN}/?host=${SUMO_HOST}
